export const SEARCH = 'SEARCH';
export const SEARCH_FULFILLED = 'SEARCH_FULFILLED';
export const SEARCH_REJECTED = 'SEARCH_REJECTED';
export const GET_REPORT = 'GET_REPORT';
export const GET_REPORT_FULFILLED = 'GET_REPORT_FULFILLED';
export const GET_REPORT_REJECTED = 'GET_REPORT_REJECTED';